# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 瞻彼淇奥
subtitle: When your dreams come alive you're unstoppable
description: 瞻彼淇奥的学习博客，编程和生活，不可或缺。
author: 瞻彼淇奥
email: 3013568147@qq.com
language: zh-CN
timezone: Asia/Shanghai
keywords: " 后台开发,python爬虫, js,javascript,java, 开发者, 程序猿, 程序媛, 极客, 编程, 代码, 开源, IT 网站, Developer,Programmer,Coder,Geek,java,python,php 用户体验 "

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://yawuplus.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: 
  - about/*
  # -bookmark/*
  - baidu_verify_Wo5mh3ARU8.html

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: 
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 5
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:
  # Archives
  #2: 开启分页
  #1: 禁用分页
  #0: 全部禁用
  archive: 1
  category: 1
  tag: 1
# Server
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 4000
server_ip: localhost
logger: false
logger_format: dev

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 7
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: landscape
theme: yilia
# search
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo:
      git: git@github.com:yawuplus/yawuplus.github.io.git
      # coding: git@git.coding.net:qiyuplus/blog.git
  branch: master

plugins:
    hexo-generator-feed
feed:
    type: atom
    path: atom.xml
    limit: 100

jsonContent:
  meta: false
  pages: false
  posts:
    title: true
    date: true
    path: true
    text: false
    raw: false
    content: false
    slug: false
    updated: false
    comments: false
    link: false
    permalink: false
    excerpt: false
    categories: false
    tags: true

symbols_count_time:
  symbols: false
  time: true
  total_symbols: true
  total_time: true
  exclude_codeblock: false

auto_category:
 enable: true
 depth: 

lazyload:
  enable: false
  thumbPath: '/images/thumb'
  # className: #optional e.g. .J-lazyload-img
  # loadingImg: #optional eg. /images/loading.png

lightgallery:
    # if you don't specify the css or js source, the default cdn will be used.
    # css: # css source url
    # js: #js source url
    # sorry that I can not find any cdn hosting following plugins,
    # please self-host the plugin js and add url here
    # plugins:
        # lg-thumbnail:
        # lg-zoom:
        # lg-autoplay:
        # lg-fullscreen:
        # lg-pager:

# # Hexo Beautify
# beautify:
#   types:
#     - html
#     - css
#     - js
#   exclude:
#     - '*.min.css'
#     - '*.min.js'
#   html:
#     'indent_inner_html': false
#     'indent_size': 2
#     'indent_with_tabs': false
#     # More Options (https://github.com/beautify-web/js-beautify/blob/master/README.md)
#   css:
#     'indent_size': 2
#     'newline_between_rules': true
#     'indent_with_tabs': false
#     # More Options (https://github.com/beautify-web/js-beautify/blob/master/README.md)
#   js:
#     'indent_size': 2
#     'indent_with_tabs': false
#     # More Options (https://github.com/beautify-web/js-beautify/blob/master/README.md)

gitment:
  enable: false
  githubID: yawuplus
  repo: https://github.com/yawuplus/blog-comments.git
  ClientID: 06c00a42e10f0cf813d9
  ClientSecret: 643756d633a58e516202086029eb41a3413182ef
  lazy: true

sitemap:
    path: sitemap.xml
#baidusitemap:
#path: baidusitemap.xml
#sitemap:
#    path: sitemap.xml
baidusitemap:
    path: baidusitemap.xml
