name: deploy to aliyun oss

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Build my hexo blog
      run: |
        echo start deploy blog
        cd blog
        npm install
        npm install -g hexo-cli
        hexo clean
        hexo generate
    - uses: manyuanrong/setup-ossutil@v1.0
      with: 
        endpoint: "oss-cn-shenzhen.aliyuncs.com" 
        access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
    - name: Deploy my blog to aliyun oss
      run: 
          ossutil cp blog/public oss://minicloudsky -rf
